env:
  browser: true
  es2021: true
  jest: true
  commonjs: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never

  # Specs
  jest/no-disabled-tests: error
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
