require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/leases", type: :request do
  # Lease. As you add validations to Lease, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Lease.create! valid_attributes
      get leases_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lease = Lease.create! valid_attributes
      get lease_url(lease)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    skip "renders a successful response" do
      get new_lease_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      lease = Lease.create! valid_attributes
      get edit_lease_url(lease)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lease" do
        expect do
          post leases_url, params: { lease: valid_attributes }
        end.to change(Lease, :count).by(1)
      end

      it "redirects to the created lease" do
        post leases_url, params: { lease: valid_attributes }
        expect(response).to redirect_to(lease_url(Lease.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lease" do
        expect do
          post leases_url, params: { lease: invalid_attributes }
        end.to change(Lease, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post leases_url, params: { lease: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested lease" do
        lease = Lease.create! valid_attributes
        patch lease_url(lease), params: { lease: new_attributes }
        lease.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the lease" do
        lease = Lease.create! valid_attributes
        patch lease_url(lease), params: { lease: new_attributes }
        lease.reload
        expect(response).to redirect_to(lease_url(lease))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        lease = Lease.create! valid_attributes
        patch lease_url(lease), params: { lease: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lease" do
      lease = Lease.create! valid_attributes
      expect do
        delete lease_url(lease)
      end.to change(Lease, :count).by(-1)
    end

    it "redirects to the leases list" do
      lease = Lease.create! valid_attributes
      delete lease_url(lease)
      expect(response).to redirect_to(leases_url)
    end
  end
end
