require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tickets", type: :request do
  # Ticket. As you add validations to Ticket, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Ticket.create! valid_attributes
      get tickets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ticket = Ticket.create! valid_attributes
      get ticket_url(ticket)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    skip "renders a successful response" do
      get new_ticket_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ticket = Ticket.create! valid_attributes
      get edit_ticket_url(ticket)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ticket" do
        expect do
          post tickets_url, params: { ticket: valid_attributes }
        end.to change(Ticket, :count).by(1)
      end

      it "redirects to the created ticket" do
        post tickets_url, params: { ticket: valid_attributes }
        expect(response).to redirect_to(ticket_url(Ticket.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ticket" do
        expect do
          post tickets_url, params: { ticket: invalid_attributes }
        end.to change(Ticket, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tickets_url, params: { ticket: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested ticket" do
        ticket = Ticket.create! valid_attributes
        patch ticket_url(ticket), params: { ticket: new_attributes }
        ticket.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ticket" do
        ticket = Ticket.create! valid_attributes
        patch ticket_url(ticket), params: { ticket: new_attributes }
        ticket.reload
        expect(response).to redirect_to(ticket_url(ticket))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ticket = Ticket.create! valid_attributes
        patch ticket_url(ticket), params: { ticket: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ticket" do
      ticket = Ticket.create! valid_attributes
      expect do
        delete ticket_url(ticket)
      end.to change(Ticket, :count).by(-1)
    end

    it "redirects to the tickets list" do
      ticket = Ticket.create! valid_attributes
      delete ticket_url(ticket)
      expect(response).to redirect_to(tickets_url)
    end
  end
end
