name: JS Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development


jobs:
  js_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Yarn install and compile
        run: |
          yarn
          bundle exec rails webpacker:compile

      - name: Run tests
        run: yarn jest
