name: System Test

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  POSTGRES_HOST_AUTH_METHOD: trust
  PGUSER: postgres
  PGHOST: localhost

jobs:
  system_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Create db and compile app
        run: |
          yarn
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rails webpacker:compile

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Server
        run: CYPRESS=1 bin/rails server -p 5017 -d
      - name: Pause
        run: sleep 10s
      - name: Prepare
        run: |
          curl 'http://localhost:5017/'
          sleep 30s
      - name: Run tests
        run: yarn cypress run
